### ISSUE TITLE
vagrant env build

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/scf#1000]
Please document the need for Base Development (pattern) and libvirt-devel for the vagrant-libvirt plugin to install successfully.

**Comment by aarondl** [comment]
The installation of libvirt and vagrant is not covered by the documentation in this repo intentionally. We would not be able to properly maintain this documentation and it'd stagnate quickly, also there are more ways that the above to install libvirt/vagrant. For these instructions it's best to use the documentation available from each of the products involved: The OS you're using (not always SUSE), libvirt, and vagrant in order to get the right pieces put together to run the vagrant box.
