### ISSUE TITLE
The syntax of ((^HCP_COMPONENT_INDEX)) ((/HCP_COMPONENT_INDEX)) ((#HCP_COMPONENT_INDEX))

### ISSUE THREAD

**Issue by jianqiu** [SUSE/scf#1072]
Could you please explain the syntax for ((^HCP_COMPONENT_INDEX))and ((/HCP_COMPONENT_INDEX)) in role-manifest.yaml
what is the value of "index" if HCP_COMPONENT_INDEX=0? Thanks!
index: ((HCP_COMPONENT_INDEX))((^HCP_COMPONENT_INDEX))0((/HCP_COMPONENT_INDEX))

**Comment by aarondl** [comment]
Hey there @jianqiu. We use a mustache templating system so all the relevant documentation should be here:
https://mustache.github.io/mustache.5.html

We use `(())` for delimiters because `{{}}` being used by other things too close to the system.

The excerpt from those docs that applies is:
> Inverted Sections
> An inverted section begins with a caret (hat) and ends with a slash. That is {{^person}} begins a "person" inverted section while {{/person}} ends it.
>
> While sections can be used to render text one or more times based on the value of the key, inverted sections may render text once based on the inverse value of the key. That is, they will be rendered if the key doesn't exist, is false, or is an empty list.

I believe this solves the question here. Re-open if there's some issue. Also join us on #fissile in Cloud Foundry slack for quick questions like this :)
