### ISSUE TITLE
the stemcell of  fissile-stemcell-ubuntu does not have jq installed

### ISSUE THREAD

**Issue by jianqiu** [SUSE/scf#1081]
There is no jq installed in the stemcell of  fissile-stemcell-ubuntu:trusty-7.ga393242-2.3

**Comment by viovanov** [comment]
@jianqiu is that a prerequisite for something?

**Comment by jianqiu** [comment]
@viovanov  the following script needs jq
https://github.com/SUSE/scf/blob/develop/container-host-files/etc/hcf/config/scripts/configure-HA-hosts.sh

**Comment by viovanov** [comment]
@jianqiu yes, I see that now - we don't see the problem because the kube API is available when running things. Can I ask how you're deploying that the kube API isn't available?

**Comment by mook-as** [comment]
Umm, we don't see the problem because we install jq in the [SUSE stemcell](https://github.com/SUSE/fissile-stemcell-openSUSE/blob/42.2/Dockerfile#L17). We should either [install it](https://github.com/SUSE/bosh-linux-stemcell-builder/blob/opensuse_stemcell/stemcell_builder/stages/base_ubuntu_packages/apply.sh) or drop the requirement and use something not-jq…

**Comment by alexjh** [comment]
Hi @jianqiu! My PR to remove the requirement for jq landed today:
https://github.com/SUSE/scf/pull/1268
