### ISSUE TITLE
Does new Garden still support nested container when using SCF?

### ISSUE THREAD

**Issue by zhangtbj** [SUSE/scf#1129]
Hi,

I heard from community that Garden will use the overlayFS2 for the Storage Driver so that the Garden is not supported using on Kubernetes as nested container (container on container)

```
garden is using (IIRC) aufs, and that seems to work (sometimes) over aufs, maybe even sometimes over overlay for reasons we cannot identify (it "shouldn't" work)

When garden switches to overlay, overlay checks to see, "am I nested" and pukes if isNested == true
```

So do you know this change? And can SCF still work fine if using the new Garden on Kube?

Thanks!

**Comment by zhangtbj** [comment]
Hi @mook-as and @aarondl ,

Do you know the answer? Thanks a lot! :)

**Comment by mook-as** [comment]
Hi @zhangtbj 
Sorry, we're not a real-time support system so we couldn't answer within an hour outside of work hours.

I'll look at this a bit later. Thanks.

**Comment by zhangtbj** [comment]
Sure thing @mook-as .

Thanks a lot!

**Comment by mook-as** [comment]
Hi @zhangtbj,

We haven't been running on AUFS for a bit (since that's not included in openSUSE, and we've been using that for the base).  The docker (on the vagrant VM, at least) should be using [overlay2] on [ext4] to run kubernetes; the garden containers are btrfs (and a bit of overlay, it looks like).

Since this repo is _already_ all CF-on-kubernetes it should have been possible to spin up a VM to test it out…

[overlay2]: https://github.com/SUSE/scf/blob/5b8eedcbb4a529e6485b8474f3a24f7f93061aad/packer/http/docker.conf#L3
[ext4]: https://github.com/SUSE/scf/blob/5b8eedcbb4a529e6485b8474f3a24f7f93061aad/packer/http/autoyast.xml#L68
