### ISSUE TITLE
acceptance-tests on CaaSP v2

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/scf#1145]
host-192-168-123-38:~/deploy # kubectl create    --namespace=scf    --filename="kube/cf/bosh-task/acceptance-tests.yaml"

Error from server (BadRequest): error when creating "kube/cf/bosh-task/acceptance-tests.yaml": Pod in version "v1" cannot be handled as a Pod: [pos 818]: json: expect char '"' but got char '2'

**Comment by abonillasuse** [comment]
Also in GKE - looks like a manifest bug
alejandro_bonilla@cloudshell:~/deploy$ kubectl create    --namespace=scf    --filename="kube/cf/bosh-task/acceptance-tests.yaml"
Error from server (BadRequest): error when creating "kube/cf/bosh-task/acceptance-tests.yaml": Pod in version "v1" cannot be handled as a Pod: [pos 818]: json: expect char '"' but got char '2'

**Comment by mook-as** [comment]
Could you attach the failing yaml file so we could actually be sure we're looking at the same issues? Thanks!

**Comment by abonillasuse** [comment]
It's the one in the latest release.

**Comment by aarondl** [comment]
This is a known issue and should be fixed in later releases. We didn't fix it retroactively because we didn't anticipate anyone would be running the tests outside our team. I'll close this, but if you need to run them for some reason (keep it mind these tests are destructive and leave stuff all over your cluster that you don't want - so it's unlikely you want to run them!) let us know, we can probably just hand you an updated file.
