### ISSUE TITLE
Should diego-api be statefulset or deployment and have multiple ones?

### ISSUE THREAD

**Issue by zhangtbj** [SUSE/scf#1211]
Hi all,

I see you change the name of diego-database to diego-api (although I don't know why:)), and you remove the volume. But the diego-api without volume will change from statefulset to deployment.

I am not sure if it is as design. But I think there is one error in bbs.json config is:
```
"advertise_url":"https://diego-api-184916.diego-api-set.cf.svc.cluster.local:8889"
```
From the name of `diego-api-set` I think this diego-api should be the statefulset, I am not sure if there is any error if use wrong advertise_url.

**But my real problem is:** 
Have you tried to have multiple diego-api? (CF officially suggest have >=2 diego-api for HA)

I have tried to have two diego-api by using both deployment and statefulset, ONLY diego-api-0 can startup and work, because the readiness of others are fail (bbs job is not start correctly and 8889 port is not on).

I check the bbs log and found that the bbs startup is hang at the beginning to get consul lock:
```
{"timestamp":"1511534594.314656019","source":"bbs","message":"bbs.consul-lock.acquiring-lock","log_level":1,"data":{"key":"v1/locks/bbs_lock","session":"2","value":"{\"id\":\"897f63fc-90dd-4c38-510a-f479e8a59b6d\",\"url\":\"https://diego-api-1.diego-api-set.cf.svc.cluster.local:8889\"}"}}
```

I think because diego-api-0 is holding the lock, and I also see an issue about this:
https://github.com/cloudfoundry/diego-release/issues/201

In our CF env on VM, we can have two BBS/diego-api, but I really don't know why we cannot have multiple diego-api on SCF.

Can you give me some suggestion? Thank you so much!

**Comment by aarondl** [comment]
@mook-as explained the locks and how they work on Slack. The way "active/passive" roles work in SCF is that the currently passive roles remain in a "not ready" state in Kube to avoid routing traffic to them. So this is intentional. If the first one dies, another one will grab the consul lock, become "ready" in Kube, and begin having traffic routed to it. Fulfilling the active/passive style of HA.

The advertise_url may actually be a problem though. Will leave this opened so we look into that.

**Comment by zhangtbj** [comment]
Hi @aarondl Thanks for the quick response. I also replied in Slack for the detail.

1, Why CF which is deployed by BOSH can have multiple diego-api, but SCF cannot, is there any limitation?

2, For this design, we can only use deployment, because statefulset of diego-api only make diego-api-0 work orderly.

Thanks a lot. :)

**Comment by zhangtbj** [comment]
Hi @mook-as and @aarondl ,

The same question about diego-brain:

Only allow to start one instance because the consul lock:
```
{"timestamp":"1511759161.824683666","source":"auctioneer","message":"auctioneer.consul-lock.acquiring-lock","log_level":1,"data":{"key":"v1/locks/auctioneer_lock","session":"1","value":"{\"auctioneer_id\":\"07575b7f-06d8-4ac8-5c2d-5e46497bb335\",\"auctioneer_address\":\"http://172.30.123.30:9016\"}"}}
```

**Comment by aarondl** [comment]
@zhangtbj I think you're misunderstanding something about CF. These roles (even as deployed by BOSH) are active/passive by nature. Even in a BOSH deployment, they hold a consul lock, and do not do anything until the active process releases or times out on renewing the lock inside consul. The intention here is to have many, and there's nothing wrong with it (it just doesn't show ready because it's not ready to accept traffic - this is a true fact). The only difference between BOSH and Fissile deployed CF in this regard is that it's _visible_ that the roles are not participating, whereas in a BOSH deployment even though the same thing is true, it's simply not shown to you.

The reason we use statefulsets for these roles is because we need them to ensure that the volumes stay in place, without this, we cannot get the correct data back in the event of the pod being brought up on a different node, so we can't switch to deployments.

**Comment by zhangtbj** [comment]
Hi @aarondl , Sorry, Yes, my mistake, thanks for the clarify. 

But for the statefulsets, I think you have already modified to use deployment right now for diego-api:
https://github.com/SUSE/scf/blob/develop/container-host-files/etc/hcf/config/role-manifest.yml#L378

Yes, you use volumes for diego-api before, but in this commit:
https://github.com/SUSE/scf/commit/97e20afb6904eb7bd6cc2d0188c5d12d83019a67
You have removed the volumes, and you didn't use cluster tag `tags: ['clustered']` for diego-api.

So after deployment, the diego-api will be a deployment. then you will see the `advertise_url` in bbs.json starts with the pod name `diego-api-184916` of deployment:
```
"advertise_url":"https://diego-api-184916.diego-api-set.cf.svc.cluster.local:8889"
```

I also discussed it with @viovanov on Slack. Please let me know if I mis-understand again. Thanks a lot! :)

**Comment by alexjh** [comment]
@zhangtbj Hi Jordan, I was looking into this yesterday and from what I can see, that URL is only used as a unique identifier for the lock in consul.

https://github.com/cloudfoundry/bbs/blob/407a2d0b2bd36b4631ba147b45de2b3faa7dda71/cmd/bbs/main.go#L532

I agree that having `diego-api-set` in the URL when it's not a StatefulSet is confusing, so I've made a PR to clean that up.

https://github.com/SUSE/scf/pull/1226

I've done some testing by having three diego-api roles and manually killing the BBS process in the active pod, and observed the lock TTL timing out, and a new diego-api becoming active. This works correctly from what I can see.


I agree that having some pods show up as not being Ready is confusing, but I don't know how this can be avoided right now. I tried some experiments using the healthcheck port instead, but this doesn't work. If they are 'Ready' according to Kubernetes, they will have traffic routed to them, which we do not want to happen for an active/passive role like BBS.

**Comment by zhangtbj** [comment]
Hi @alexjh Thanks for the update. I agree it cannot show Ready as before, I think it is fine if we document it for user.

I see your commit, so you are agree to keep use deployment for diego-api and change the `properties.diego.bbs.advertisement_base_hostname` properties, right?

If yes, I will also change diego-api back to deployment in my environment.

Thanks! :)
