### ISSUE TITLE
helm delete does not remove generated secrets

### ISSUE THREAD

**Issue by drnic** [SUSE/scf#1877]
I was changing my base DNS and redeploying but inside `router-0` I was seeing errors from bad x509 certs that contained the old domains. I guessed deleting + reinstalling wasn't recreating the secrets?

I can confirm that deleting the helm chart installations does not delete the generated secrets.

```
$ eirini helm delete cf --purge
release "cf" deleted
$ eirini helm delete uaa --purge
release "uaa" deleted
$ kubectl get secrets --all-namespaces
NAMESPACE     NAME                                             TYPE                                  DATA   AGE
cf            default-token-29hjx                              kubernetes.io/service-account-token   3      1h
cf            secrets-2.14.0-1                                 Opaque                                157    1h
...
uaa           default-token-7bq9k                              kubernetes.io/service-account-token   3      2h
uaa           secrets-2.14.0-1                                 Opaque                                26     1h
```

Perhaps a corollary is that deleting the charts does not delete the namespaces, which would have deleted the secrets?

**Comment by jandubois** [comment]
It is correct that `helm delete` will not delete the configmap and versioned secret created by the scf-secrets-generator, simply because it doesn't know about them.

However, they are explicitly ignored when you `helm install` a fresh copy into a reused namespace:

https://github.com/SUSE/scf-secret-generator/blob/develop/secrets/secrets.go#L164-L176

They are only being used during a `helm upgrade`.

The secrets generator gets the information about install vs. upgrade directly from helm via an environment variable:

```
        - name: "HELM_IS_INSTALL"
          value: {{ .Release.IsInstall | quote }}
```
