### ISSUE TITLE
Logs not rotated on SCF containers

### ISSUE THREAD

**Issue by mnitchev** [SUSE/scf#2343]
We ssh-ed on the api-group and cc-uploader containers and saw that there are logs that are not rotated. For example the tps logs on cc-uploader have grown to 17GB. We saw no cron jobs on the container and `rsyslogd` is reported as running by monit.

The stemcell that we used is: FISSILE_STEMCELL=splatform/fissile-stemcell-opensuse:42.3-24.g63783b3-30.60

BR,
@akshaymankar && @mnitchev

**Comment by mudler** [comment]
Hi, 

We are tracking this Issue in our board, seems to be something new that we didn't saw happening in our deployments. Can you please provide more information about the setup? e.g. if It is SCF based off from the devel branch or a tagged release, what kubernetes version are you running, storageclass used

Thanks

**Comment by alex-slynko** [comment]
Hi @mudler ,

We are using customized 2.14 on that cluster with [a custom recent version of CAPI](https://github.com/JulzDiverse/capi-release). It has only changes to the cloud controller.  Our Kubernetes version is 1.11.9 with containerd (we use IKS).
We use hostpath as a storage class for shared storage and ibm block storage for mysql.

**Comment by jimmykarily** [comment]
It turns out that a change we introduced for the bosh stemcells made it to the fissile stemcell as well: https://github.com/SUSE/bosh-linux-stemcell-builder/commit/2e4b3c8423a16d9650e0d1db563c5a4ca0edd752#diff-1a4c615dc9bcaa2cf6cb95ce8228c19eR22

This moves the rotation responsibility to systemd (which works on vms) but systemd is not running inside the pods. We should be using cron inside the containers. We are working on a proper fix. Stay tuned.

**Comment by thardeck** [comment]
Thanks for the report. The issue is fixed in the current develop branch and will be fixed in the next release.
